name: Terraform Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:     
      - 'projects/02-azure-cloudeteer-launchpad-demo/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'projects/02-azure-cloudeteer-launchpad-demo/**'

permissions:
  id-token: write 
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: prod-azure
      url: https://github.com/keenapps/terraform/tree/main/projects/02-azure-cloudeteer-launchpad-demo
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUB_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_runner_github_repo: terraform
    steps:
    - uses: actions/checkout@v4
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0
    
    - name: Terraform Init
      working-directory: ./projects/02-azure-cloudeteer-launchpad-demo
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./projects/02-azure-cloudeteer-launchpad-demo
      run: terraform plan
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./projects/02-azure-cloudeteer-launchpad-demo
      run: terraform apply -auto-approve
